// <auto-generated />
using System;
using KYX.DocEngine.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KYX.DocEngine.API.Migrations
{
    [DbContext(typeof(DocEngineDbContext))]
    [Migration("20260323172334_UseTbLogRequisicao")]
    partial class UseTbLogRequisicao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.DocumentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CentroCusto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("centro_custo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_data");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_arquivo");

                    b.Property<long?>("ProcessingTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_time_ms");

                    b.Property<string>("RequisicaoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requisicao_id");

                    b.Property<string>("ResultBase64")
                        .HasColumnType("text")
                        .HasColumnName("result_base64");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_document_jobs");

                    b.HasIndex("RequisicaoId")
                        .HasDatabaseName("ix_document_jobs_requisicao_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_document_jobs_template_id");

                    b.ToTable("document_jobs", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.LogRequisicao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canal");

                    b.Property<string>("CentroCusto")
                        .HasColumnType("text")
                        .HasColumnName("centro_custo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<string>("RequisicaoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requisicao_id");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int?>("StatusHttp")
                        .HasColumnType("integer")
                        .HasColumnName("status_http");

                    b.Property<int?>("TempoRespostaMs")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_resposta_ms");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_log_requisicao");

                    b.HasIndex("Canal")
                        .HasDatabaseName("ix_tb_log_requisicao_canal");

                    b.HasIndex("CentroCusto")
                        .HasDatabaseName("ix_tb_log_requisicao_centro_custo");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_tb_log_requisicao_criado_em");

                    b.HasIndex("RequisicaoId")
                        .HasDatabaseName("ix_tb_log_requisicao_requisicao_id");

                    b.ToTable("tb_log_requisicao", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RequiredFields")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_fields");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_templates_slug");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.DocumentJob", b =>
                {
                    b.HasOne("KYX.DocEngine.API.Models.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_jobs_templates_template_id");

                    b.Navigation("Template");
                });
#pragma warning restore 612, 618
        }
    }
}
