// <auto-generated />
using System;
using KYX.DocEngine.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KYX.DocEngine.API.Migrations
{
    [DbContext(typeof(DocEngineDbContext))]
    [Migration("20260323174341_MapPlataformaKyxTabelas")]
    partial class MapPlataformaKyxTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Consumo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canal");

                    b.Property<string>("CentroCusto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("centro_custo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("IntegracaoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("integracao_id");

                    b.Property<string>("RequisicaoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requisicao_id");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_tb_consumo");

                    b.HasIndex("Canal")
                        .HasDatabaseName("ix_tb_consumo_canal");

                    b.HasIndex("CentroCusto")
                        .HasDatabaseName("ix_tb_consumo_centro_custo");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_tb_consumo_criado_em");

                    b.HasIndex("IntegracaoId")
                        .HasDatabaseName("ix_tb_consumo_integracao_id");

                    b.HasIndex("RequisicaoId")
                        .HasDatabaseName("ix_tb_consumo_requisicao_id");

                    b.ToTable("tb_consumo", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.DocumentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CentroCusto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("centro_custo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_data");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_arquivo");

                    b.Property<long?>("ProcessingTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_time_ms");

                    b.Property<string>("RequisicaoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requisicao_id");

                    b.Property<string>("ResultBase64")
                        .HasColumnType("text")
                        .HasColumnName("result_base64");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_document_jobs");

                    b.HasIndex("RequisicaoId")
                        .HasDatabaseName("ix_document_jobs_requisicao_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_document_jobs_template_id");

                    b.ToTable("document_jobs", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Integracao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canal");

                    b.Property<string>("Credenciais")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credenciais");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Provedor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provedor");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("UrlBase")
                        .HasColumnType("text")
                        .HasColumnName("url_base");

                    b.HasKey("Id")
                        .HasName("pk_tb_integracao");

                    b.ToTable("tb_integracao", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.LogIntegracao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("IntegracaoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("integracao_id");

                    b.Property<string>("Metodo")
                        .HasColumnType("text")
                        .HasColumnName("metodo");

                    b.Property<string>("RequestBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_body");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_headers");

                    b.Property<string>("RequisicaoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requisicao_id");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<string>("ResponseHeaders")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_headers");

                    b.Property<int?>("StatusHttp")
                        .HasColumnType("integer")
                        .HasColumnName("status_http");

                    b.Property<int?>("TempoRespostaMs")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_resposta_ms");

                    b.HasKey("Id")
                        .HasName("pk_tb_log_integracao");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_tb_log_integracao_criado_em");

                    b.HasIndex("IntegracaoId")
                        .HasDatabaseName("ix_tb_log_integracao_integracao_id");

                    b.HasIndex("RequisicaoId")
                        .HasDatabaseName("ix_tb_log_integracao_requisicao_id");

                    b.ToTable("tb_log_integracao", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.LogRequisicao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canal");

                    b.Property<string>("CentroCusto")
                        .HasColumnType("text")
                        .HasColumnName("centro_custo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<string>("RequisicaoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requisicao_id");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int?>("StatusHttp")
                        .HasColumnType("integer")
                        .HasColumnName("status_http");

                    b.Property<int?>("TempoRespostaMs")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_resposta_ms");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_log_requisicao");

                    b.HasAlternateKey("RequisicaoId")
                        .HasName("ak_tb_log_requisicao_requisicao_id");

                    b.HasIndex("Canal")
                        .HasDatabaseName("ix_tb_log_requisicao_canal");

                    b.HasIndex("CentroCusto")
                        .HasDatabaseName("ix_tb_log_requisicao_centro_custo");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_tb_log_requisicao_criado_em");

                    b.HasIndex("RequisicaoId")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_log_requisicao_requisicao_id");

                    b.ToTable("tb_log_requisicao", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.NotificacaoTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canal");

                    b.Property<string>("ConteudoHtml")
                        .HasColumnType("text")
                        .HasColumnName("conteudo_html");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Variaveis")
                        .HasColumnType("jsonb")
                        .HasColumnName("variaveis");

                    b.HasKey("Id")
                        .HasName("pk_tb_template");

                    b.ToTable("tb_template", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Perfil", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tb_perfil");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_tb_perfil_nome");

                    b.ToTable("tb_perfil", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.PerfilRole", b =>
                {
                    b.Property<string>("PerfilId")
                        .HasColumnType("text")
                        .HasColumnName("perfil_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.HasKey("PerfilId", "RoleId")
                        .HasName("pk_tb_perfil_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_tb_perfil_role_role_id");

                    b.ToTable("tb_perfil_role", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tb_role");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_tb_role_nome");

                    b.ToTable("tb_role", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RequiredFields")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_fields");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_templates_slug");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("PerfilId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("pk_tb_usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_usuario_email");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_tb_usuario_perfil_id");

                    b.ToTable("tb_usuario", (string)null);
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Consumo", b =>
                {
                    b.HasOne("KYX.DocEngine.API.Models.Entities.Integracao", "Integracao")
                        .WithMany("Consumos")
                        .HasForeignKey("IntegracaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_consumo_tb_integracao_integracao_id");

                    b.HasOne("KYX.DocEngine.API.Models.Entities.LogRequisicao", "Requisicao")
                        .WithMany("Consumos")
                        .HasForeignKey("RequisicaoId")
                        .HasPrincipalKey("RequisicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_consumo_tb_log_requisicao_requisicao_id");

                    b.Navigation("Integracao");

                    b.Navigation("Requisicao");
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.DocumentJob", b =>
                {
                    b.HasOne("KYX.DocEngine.API.Models.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_jobs_templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.LogIntegracao", b =>
                {
                    b.HasOne("KYX.DocEngine.API.Models.Entities.Integracao", "Integracao")
                        .WithMany("LogIntegracoes")
                        .HasForeignKey("IntegracaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_log_integracao_tb_integracao_integracao_id");

                    b.HasOne("KYX.DocEngine.API.Models.Entities.LogRequisicao", "Requisicao")
                        .WithMany("LogIntegracoes")
                        .HasForeignKey("RequisicaoId")
                        .HasPrincipalKey("RequisicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_log_integracao_tb_log_requisicao_requisicao_id");

                    b.Navigation("Integracao");

                    b.Navigation("Requisicao");
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.PerfilRole", b =>
                {
                    b.HasOne("KYX.DocEngine.API.Models.Entities.Perfil", "Perfil")
                        .WithMany("PerfilRoles")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_perfil_role_tb_perfil_perfil_id");

                    b.HasOne("KYX.DocEngine.API.Models.Entities.Role", "Role")
                        .WithMany("PerfilRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_perfil_role_tb_role_role_id");

                    b.Navigation("Perfil");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Usuario", b =>
                {
                    b.HasOne("KYX.DocEngine.API.Models.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tb_usuario_tb_perfil_perfil_id");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Integracao", b =>
                {
                    b.Navigation("Consumos");

                    b.Navigation("LogIntegracoes");
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.LogRequisicao", b =>
                {
                    b.Navigation("Consumos");

                    b.Navigation("LogIntegracoes");
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Perfil", b =>
                {
                    b.Navigation("PerfilRoles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("KYX.DocEngine.API.Models.Entities.Role", b =>
                {
                    b.Navigation("PerfilRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
